// src/data/index.tsx
export const collectionsData = [
  {
    id: '1',
    title: 'Red Chilli',
    image: require('../assets/products/Chilli.png'),
    rating: 4.5,
    description: 'Fresh red chilli',
    categories: [
      {
        id: '1a',
        title: 'Small Red Chilli',
        image: require('../assets/products/Chilli.png'),
        description: 'Smaller variety of red chilli',
        rating: 4.3,
        weight: '500g',
      },
      {
        id: '1b',
        title: 'Small Red Chilli',
        image: require('../assets/products/Chilli.png'),
        description: 'Smaller variety of red chilli',
        rating: 4.4,
        weight: '1kg',
      },
      {
        id: '1c',
        title: 'Large Red Chilli',
        image: require('../assets/products/Chilli.png'),
        description: 'Larger, spicier red chilli',
        rating: 4.6,
        weight: '500g',
      },
      {
        id: '1d',
        title: 'Large Red Chilli',
        image: require('../assets/products/Chilli.png'),
        description: 'Larger, spicier red chilli',
        rating: 4.7,
        weight: '1kg',
      },
    ],
  },
  {
    id: '2',
    title: 'Coffee',
    image: require('../assets/products/Coffee.png'),
    rating: 4.8,
    description: 'Organic coffee beans',
    categories: [
      {
        id: '2a',
        title: 'Arabica',
        image: require('../assets/products/Coffee.png'),
        description: 'Smooth and complex Arabica beans',
        rating: 4.7,
        weight: '500g',
      },
      {
        id: '2b',
        title: 'Arabica',
        image: require('../assets/products/Coffee.png'),
        description: 'Smooth and complex Arabica beans',
        rating: 4.8,
        weight: '1kg',
      },
      {
        id: '2c',
        title: 'Robusta',
        image: require('../assets/products/Coffee.png'),
        description: 'Strong and bold Robusta beans',
        rating: 4.9,
        weight: '500g',
      },
      {
        id: '2d',
        title: 'Robusta',
        image: require('../assets/products/Coffee.png'),
        description: 'Strong and bold Robusta beans',
        rating: 4.9,
        weight: '1kg',
      },
    ],
  },
  {
    id: '3',
    title: 'Rice',
    image: require('../assets/products/Rice1.png'),
    rating: 4.3,
    description: 'Premium quality rice',
    categories: [
      {
        id: '3a',
        title: 'Basmati Rice',
        image: require('../assets/products/Rice1.png'),
        description: 'Long-grain fragrant rice',
        rating: 4.5,
        weight: '500g',
      },
      {
        id: '3b',
        title: 'Basmati Rice',
        image: require('../assets/products/Rice1.png'),
        description: 'Long-grain fragrant rice',
        rating: 4.6,
        weight: '1kg',
      },
      {
        id: '3c',
        title: 'Jasmine Rice',
        image: require('../assets/products/Rice2.png'),
        description: 'Soft and aromatic rice',
        rating: 4.2,
        weight: '500g',
      },
      {
        id: '3d',
        title: 'Jasmine Rice',
        image: require('../assets/products/Rice2.png'),
        description: 'Soft and aromatic rice',
        rating: 4.3,
        weight: '1kg',
      },
    ],
  },
  {
    id: '4',
    title: 'Turmeric',
    image: require('../assets/products/Terumeric.png'),
    rating: 4.6,
    description: 'High-quality turmeric',
    categories: [
      {
        id: '4a',
        title: 'Ground Turmeric',
        image: require('../assets/products/Terumeric.png'),
        description: 'Fine powder',
        rating: 4.4,
        weight: '500g',
      },
      {
        id: '4b',
        title: 'Ground Turmeric',
        image: require('../assets/products/Terumeric.png'),
        description: 'Fine powder',
        rating: 4.5,
        weight: '1kg',
      },
      {
        id: '4c',
        title: 'Whole Turmeric',
        image: require('../assets/products/Terumeric.png'),
        description: 'Whole turmeric root',
        rating: 4.8,
        weight: '500g',
      },
      {
        id: '4d',
        title: 'Whole Turmeric',
        image: require('../assets/products/Terumeric.png'),
        description: 'Whole turmeric root',
        rating: 4.9,
        weight: '1kg',
      },
    ],
  },
  {
    id: '5',
    title: 'Rice',
    image: require('../assets/products/Rice1.png'),
    rating: 4.3,
    description: 'Premium quality rice',
    categories: [
      {
        id: '5a',
        title: 'Basmati Rice',
        image: require('../assets/products/Rice1.png'),
        description: 'Long-grain fragrant rice',
        rating: 4.5,
        weight: '500g',
      },
      {
        id: '5b',
        title: 'Basmati Rice',
        image: require('../assets/products/Rice1.png'),
        description: 'Long-grain fragrant rice',
        rating: 4.6,
        weight: '1kg',
      },
      {
        id: '5c',
        title: 'Jasmine Rice',
        image: require('../assets/products/Rice2.png'),
        description: 'Soft and aromatic rice',
        rating: 4.2,
        weight: '500g',
      },
      {
        id: '5d',
        title: 'Jasmine Rice',
        image: require('../assets/products/Rice2.png'),
        description: 'Soft and aromatic rice',
        rating: 4.3,
        weight: '1kg',
      },
    ],
  },
  {
    id: '6',
    title: 'Turmeric',
    image: require('../assets/products/Turmeric.png'),
    rating: 4.6,
    description: 'High-quality turmeric',
    categories: [
      {
        id: '6a',
        title: 'Ground Turmeric',
        image: require('../assets/products/Turmeric.png'),
        description: 'Fine powder',
        rating: 4.4,
        weight: '500g',
      },
      {
        id: '6b',
        title: 'Ground Turmeric',
        image: require('../assets/products/Turmeric.png'),
        description: 'Fine powder',
        rating: 4.5,
        weight: '1kg',
      },
      {
        id: '6c',
        title: 'Whole Turmeric',
        image: require('../assets/products/Turmeric.png'),
        description: 'Whole turmeric root',
        rating: 4.8,
        weight: '500g',
      },
      {
        id: '6d',
        title: 'Whole Turmeric',
        image: require('../assets/products/Turmeric.png'),
        description: 'Whole turmeric root',
        rating: 4.9,
        weight: '1kg',
      },
    ],
  },
  {
    id: '7',
    title: 'Corn',
    image: require('../assets/products/Corn.png'),
    rating: 4.7,
    description: 'Fresh corn on the cob',
    categories: [
      {
        id: '7a',
        title: 'Baby Corn',
        image: require('../assets/products/Corn.png'),
        description: 'Small, tender baby corn',
        rating: 4.6,
        weight: '500g',
      },
      {
        id: '7b',
        title: 'Baby Corn',
        image: require('../assets/products/Corn.png'),
        description: 'Small, tender baby corn',
        rating: 4.7,
        weight: '1kg',
      },
      {
        id: '7c',
        title: 'Regular Corn',
        image: require('../assets/products/Corn.png'),
        description: 'Standard size corn on the cob',
        rating: 4.5,
        weight: '500g',
      },
      {
        id: '7d',
        title: 'Regular Corn',
        image: require('../assets/products/Corn.png'),
        description: 'Standard size corn on the cob',
        rating: 4.6,
        weight: '1kg',
      },
    ],
  },
];
